site_name: EasyMB

site_url: http://easymb.xyz/

theme:
    logo: assets/logo.svg
    favicon: assets/favicon.png
    ##name: mkdocs
    name: material
    ##name: 'rtd-dropdown'
    ##name: ivory
    ##name: bootstrap4
    #name: swan
    ##name: windmill
    ##name: gitbook
    #name: readthedocs
    hljs_languages:
        - json
        - shell

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite


plugins:

    - awesome-pages:
        strict: true
        collapse_single_pages: true
    - section-index
