site_name: EasyMB

site_url: http://easymb.xyz/

theme:
    ##name: mkdocs
    name: material
    ##name: 'rtd-dropdown'
    ##name: ivory
    ##name: bootstrap4
    #name: swan
    ##name: windmill
    ##name: gitbook
    
    #name: readthedocs
    avigation_depth: 7
    hljs_languages:
        - json
        - shell

#theme:
#    name: null
#    custom_dir: 'cinder/'

# markdown_extensions:
#     - toc:
#         permalink: True

markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite


plugins:
    #- search
    - awesome-pages:
        strict: true
        collapse_single_pages: true
    - section-index

# nav:
#     - Введение: index.md
#     - CLI: cli.md
#     - Конфигурирование:
#         - Обычный режим: 
#             - REST API : 
#                 - config/normal/restapi/example.md
#                 - restapi: config/normal/restapi/restapi.md
#                 - accessList: config/normal/restapi/accessList/accessList.md
#             - Links: 
#                 - Пример: config/normal/links/example.md
#                 - links: config/normal/links/links.md

#         - Тестовый режим : config/test/test.md