site_name: EasyMB

site_url: http://easymb.xyz/

theme:
    #name: mkdocs
    #name: material
    #name: ivory
    #name: bootstrap4
    #name: swan
    name: readthedocs
    navigation_depth: 10
    custom_dir: site/

nav:
    - Введение: index.md
    - CLI: cli.md
    - Конфигурирование:
        - Обычнвй режим: 
            - REST API : config/normal/restapi.md
            - Links: config/normal/links.md
        - Тестовый режим : config/test/test.md